### ISSUE TITLE
it doesent work

### ISSUE THREAD

**Issue by DarkAngel17186** [Flemmli97/VillagerTrades#2]
### Modloader

Forge

### Minecraft version

1.21

### Modloader version

21.0.42

### Mod version

1.21

### Description

i cant type /villagertrades edit fletcher     edit and fletcher are red

### Steps to reproduce

1. Step one

### Logs

there is no log

**Comment by Flemmli97** [comment]
1. you need op for the commands
2. the command edits existing mobs so you need to pass in an existing villager. e.g. by tab autocomplete while looking at the villager
